// <auto-generated />
using AaronUrkinCodeExample.DataAccessLayer.Localization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AaronUrkinCodeExample.DataAccessLayer.Localization.Migrations
{
    [DbContext(typeof(LocalizationDbContext))]
    [Migration("20180607053756_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("exmpl_localization")
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AaronUrkinCodeExample.DataAccessLayer.Localization.Entities.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(17);

                    b.Property<string>("Key");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(512);

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("CultureCode", "Scope", "Key")
                        .IsUnique()
                        .HasFilter("[Key] IS NOT NULL");

                    b.ToTable("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
